### ISSUE TITLE
Todo List buat semua

### ISSUE THREAD

**Issue by chez14** [sagut-obda/dokumen#1]
Hi semua,

Kali ini gw bakal coba listing semua jobdesknya, dan gw buatkan issue satu per satu. (biar bisa pake fitur Milestone dan kalo ada masalah bisa mention gw.)
Pertama-tama, gw bakal listing seluruh kerjaan kita, dan kita coba bagi tugas satu per satu.

## Yang wajib di lakukan oleh semua orang.
- Latihan Git
- Baca-baca JMonkey, gw masih baca-baca juga, kurang lebih katanya mirip Unity beberapa istilahnya.

## Yang butuh kita kerjakan:
| Desc | PIC | Status |
|------|-----|-------|
| Logic Designer (~~this should be easy~~ Not so easy eh) | @ferdianexe  | - |
| Asset Finder/Stealer/Creator (Music/Images) | @Eririn07 | - |
| Programmer | ~~all~~ Most of us | @chez14 still making a list of it |

Mohon kerjasamanya ya semua, deadline sekitar sebulan lagi xD

**Comment by chez14** [comment]
@ferdianexe sama @Eririn07 gw butuh bantuan buat listing kerjaan kita... wakaowk sumpah gw bingung banget kalo udah masalah game, gw [GGJB 2015](https://globalgamejam.org/2015/games/miniko) kmaren bareng @timusvpf udah lupa semua aowkoawkoawk

**Comment by chez14** [comment]
Gw nggak bisa bikin mail listingnya, ide lainnya, gw pasangin link Google Drive buat semua aja, gw udah kasih akses ke email student kalian, kalo butuh buat pake email pribadi, bilang-bilang...

Link Google Drive:

https://drive.google.com/drive/folders/0B_WpjF1ked_7WGxVaFdOTzRsZUE?usp=sharing

**Comment by ferdianexe** [comment]
sorry baru ada respond skrng :v 
kalo pake browser maxthon ini github kaya butiran debu dah :v 
buat masalah listting game udah gw buat di todo list
diperhatikan aja...
basically itu yang dibutuhin sebuah game endless game kita biar bisa jalan
asset song yang begituan termasuk sebuah utilities yang sekedar meningkatkan daya jual beli game tersebut,,,
jadi bagian itu sbenernya terlalu diperhitungkan diawal dulu buat kita kita yang mau ngejar deadline
teknik pengerjaan untuk skarang jangan terlalu mikirin masalah memory
karena game kita masih berbasis PC jadi ga perlu mikirin kebutuhan ram dlu
apalagi game ini cuman 1x endless game doang...
tapi kalo mw bagus optimize method bisa dilakuin H-3 sebelum deadline tugas xD XD
good luck gais ~
