### ISSUE TITLE
List yang perlu dipelajari dari JMonyet

### ISSUE THREAD

**Issue by chez14** [sagut-obda/dokumen#2]
Dari beberapa konsultasi sama @ferdianexe dan pengalaman jaman dulu, ada beberapa list yang penting kita pelajari sekarang:
- Bikin UI/GUI (buat menu ini maksudnya) -> [Nifty Editor](https://github.com/relu91/niftyeditor/releases/tag/nifty-editor0.5.9) | [Nifty Doc (by jMonkey)](https://jmonkeyengine.gitbooks.io/wiki-jmonkeyengine/advanced/nifty_gui_xml_layout.html)
- Bikin Scene (Gameplay disini)
- Import Model, dan ngeprogram benda itu

More Advanced:
- Obstacle Programming
- [~~damn~~ Hello Collision](https://jmonkeyengine.github.io/wiki/jme3/beginner/hello_collision.html)
- [Animating your character](https://jmonkeyengine.gitbooks.io/wiki-jmonkeyengine/beginner/hello_animation.html)
- [Playing audio](https://jmonkeyengine.github.io/wiki/jme3/advanced/audio.html), bedanya kita bakal pake [SoundCloud](https://github.com/nok/soundcloud-java-library)nya [NCS](soundcloud.com/nocopyrightsounds), (kalo bisa, kalo kagak, musiknya gw donlotinm pasang jadi static.)

Notes:
- [Best Practices](https://jmonkeyengine.gitbooks.io/wiki-jmonkeyengine/intermediate/best_practices.html) [Nggak wajib, cuma catetan aja]

List berikutnya nyusul.

**Comment by chez14** [comment]
Rencana gw, mungkin sampe rabu/jumat depan kita harusnya sudah mulai ngoding di jmonyetnya sih, berharap kita sempet ngelakuin semuanya xD

Yang masalah tentang git, kelihatannya sudah pada bisa dilepas bebas wkwk unless kmaren gw kelupaan nanyain git ke @easydisco, senin renacanya gw sama dia bakal kaya ngebahas gitnya, yang lain mungkin walau dapet masalah dikit dikit, lama lama kebiasaan wkwk

As usual, shall you have any problem, ask me to get some direction. Sementara ini gw fokusin buat ke grup kita dulu xD

**Comment by chez14** [comment]
Adding Cinematics for moving objects, it's available [here](https://hub.jmonkeyengine.org/t/move-a-object-with-animation/19290/6), but the code formatting from their site is dreadful, I'm writing it here:

**NOTE:** it's from 2011, do not expect it's working that's why I didn't put it on above, I'll try this one soon, and giving a review on it, while I'm exploring other possibilities...

```java
Cinematic cinematic = new Cinematic(object1, 5);
cinematic.addCinematicEvent(0, new PositionTrack(object1, object1.getLocalTranslation().add(500f, 0,0 ), 5, LoopMode.Loop));
stateManager.attach(cinematic);
cinematic.play();
```

**Comment by chez14** [comment]
Well, looking at [this link](https://jmonkeyengine.github.io/wiki/jme3/beginner/hello_asset.html) it felt like everything loaded from a single method, as i know, this will cause so much confusion for humans to maintain.

I'm suggesting it to split into several classes, like, load things first, then add models and etc etc etc.
But I'll discuss this openly on an issue, for now, i'll take some time to get a class design for this for the draft, so just... hang on for now...

**Comment by ferdianexe** [comment]
spirit !

**Comment by chez14** [comment]
Got Nifty Builder here~...
![image](https://user-images.githubusercontent.com/5555026/32409481-f93e0b6a-c1de-11e7-8cc8-e9f2f459df4a.png)

**Comment by chez14** [comment]
Close. The subject is long done.
